mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.woniu.domin
server:
  port: 8081
spring:
  application:
    name: coach
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/four_end?useUnicode=true&characterEncoding=utf-8
    username: root
  jackson:
    date-format: yyyy-MM-dd
  redis:
    host: 192.168.135.129
    port: 6379